// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.AppView = (function(_super) {
    __extends(AppView, _super);

    function AppView() {
      this.initialize = __bind(this.initialize, this);
      return AppView.__super__.constructor.apply(this, arguments);
    }

    AppView.prototype.template = _.template('<button class="hit-button">Hit</button> <button class="stand-button">Stand</button> <button class="new-button">New Hand</button> <div class="player-hand-container"></div> <div class="dealer-hand-container"></div>');

    AppView.prototype.events = {
      "click .hit-button": function() {
        return this.model.get('playerHand').hit();
      },
      "click .stand-button": function() {
        return this.model.get('playerHand').stand();
      },
      "click .new-button": function() {
        return this.model.newHand();
      }
    };

    AppView.prototype.initialize = function() {
      this.model.on('disableButtons', (function(_this) {
        return function() {
          return _this.disableButtons();
        };
      })(this));
      this.model.on('render', (function(_this) {
        return function() {
          return _this.render();
        };
      })(this));
      return this.render();
    };

    AppView.prototype.disableButtons = function() {
      $('.hit-button').attr('disabled', 'disabled');
      return $('.stand-button').attr('disabled', 'disabled');
    };

    AppView.prototype.render = function() {
      this.$el.children().detach();
      this.$el.html(this.template());
      this.player = new HandView({
        collection: this.model.get('playerHand')
      });
      this.dealer = new HandView({
        collection: this.model.get('dealerHand')
      });
      this.$('.player-hand-container').html(this.player.el);
      return this.$('.dealer-hand-container').html(this.dealer.el);
    };

    return AppView;

  })(Backbone.View);

}).call(this);

//# sourceMappingURL=AppView.map
