// Generated by CoffeeScript 1.7.1
(function() {
  var model, view;

  model = new App();

  view = new AppView({
    model: model
  });

  view.$el.appendTo('body');

  if (model.get('blackjack')) {
    view.disableButtons();
  }

}).call(this);

//# sourceMappingURL=main.map
